###订单服务的端口号
server:
  port: 8003
###服务别名----服务注册到注册中心名称
spring:
  application:
    name: zk-order
#    使用zookeeper做注册中心配置
  cloud:
    zookeeper:
#      注册到zk的地址
      connect-string: 127.0.0.1:2181

