###服务启动端口号
server:
  port: 8005
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: leeue-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    ###需要向eureka上注册 就设置为true
    register-with-eureka: true
    ###需要从eureka上获取注册信息
    fetch-registry: true
##   EurekaClient端配置 心跳检测与续约时间配置
##  测试时将值设置小些，保证服务关闭注册中心后能及时踢出服务
#  instance:
##    Eureka客户端向服务端发送心跳的时间间隔，单位为秒()
#    lease-renewal-interval-in-seconds: 1
##    Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过就会进行剔除。
#    lease-expiration-duration-in-seconds: 2
