###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
###网关名称
spring:
  application:
    name: leeue-service-zuul
### 配置网关反向代理
zuul:
#  配置zuul超时时间
  host:
    connect-timeout-millis: 150000
    socket-timeout-millis: 15000
  routes:
#    定义转发服务规则 可以随便写
    api-a:
      ### 以 /api-member/访问转发到会员服务 当客户端输入127.0.0.1:80/api-member开头的时候，就会转发到会员服务
      path: /api-member/**
      serviceId: leeue-member
    api-b:
      ### 以 /api-order/访问转发到订单服务 当客户端输入127.0.0.1:80/api-order开头的时候，就会转发到订单服务
#      zuul 网关默认是整合了ribbon 自动实现负载均衡轮训效果
      path: /api-order/**
#      订单服务别名
      serviceId: leeue-order


#      上面配置的意义


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000