###服务端口号
server:
  port: 8200
###eureka 基本信息配置
spring:
  application:
    name: eureka-server
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
#    instance-id: ${eureka.instance.hostname}:${server.port}:@project.version@
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/
    ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: true

  # Eureka服务保护机制配置 在服务端加EurekaServer
  server:
    # 本地或测试环境，关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000