server:
  port: 8080

####### 配置多数据源  #######
spring:
  datasource:
    ###可读数据源  都是去连 mycat
    select:
      jdbc-url: jdbc:mysql://192.168.2.7:8066/mycat_testdb
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: user
    ####可写数据源  都是去连 mycat
    update:
      jdbc-url: jdbc:mysql://192.168.2.7:8066/mycat_testdb
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
