server:
  port: 8003
#  配置服务的名称  网关名称
spring:
  application:
    name: zuul
#    配置eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

# zuul 配置反向代理
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: projectA
    api-b:
      path: /api-b/**
      serviceId: projectB


# 浏览器上输入 http://127.0.0.1:8003/api-a  就会跳转到 projectA项目上去 这个就是使用zuul网关实现

# 浏览器上输入 http://127.0.0.1:8003/api-b 就会跳转到 projectB项目上去