spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
sharding:
  jdbc:
    ####ds1
    datasource:
      names: ds0
      ds0:
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_0
        username: root
    ## shardingjdbc 分片配置
    config:
      sharding:
        tables:
          t_order:
            table-strategy:
              inline:
                #### 根据userid 进行分片
                sharding-column: user_id
                ## ds_1.t_order_0  ds_1.t_order_1
                algorithm-expression: ds_0.t_order_$->{user_id % 2}
                ## 分表总数 0-1 t_order_0 t_order_1
            actual-data-nodes: ds0.t_order_$->{0..1}
        props:
          sql:
            ### 开启分片日志
            show: true
